server:
  port: 8010
  max-http-header-size: 3048576
  tomcat: 
    max-http-post-size: 3048576
spring:
  application:
    name: aigou-common
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #common
  instance:
    prefer-ip-address: true