server:
  port: 8010
  max-http-header-size: 4048576000
  tomcat:
    max-http-post-size: 4048576000
spring:
  application:
    name: aigou-common
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300 #9200是图形界面端,9300代码端
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
