server:
  port: 8002
spring:
  application:
    name: aigou-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_product?useSSL=false
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:cn/miswang/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.miswang.aigou.domain,cn.miswang.aigou.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true